apiVersion: v1
kind: ConfigMap
metadata:
  name: easyshop-config
  namespace: easyshop
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/easyshop"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://easyshop.devopsdock.site/api"
  NEXTAUTH_URL: "https://easyshop.devopsdock.site/"
  NEXTAUTH_SECRET: "your-nextauth-secret-key"
  JWT_SECRET: "your-jwt-secret-key"
